export const listData = [
  {
    id: 1,
    address: "123 Oak Street, Fairfax, VA",
    price: 600000,
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2500,
    description: "Beautiful family home with large backyard.",
    type: "Single-family",
    yearBuilt: 2010,
    images: []
  },
  {
    id: 2,
    address: "456 Maple Avenue, Fairfax, VA",
    price: 750000,
    bedrooms: 5,
    bathrooms: 4,
    squareFeet: 3200,
    description: "Spacious house in a quiet neighborhood.",
    type: "Single-family",
    yearBuilt: 2015,
    images: []
  },
  {
    id: 3,
    address: "789 Elm Drive, Fairfax, VA",
    price: 500000,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1800,
    description: "Cozy home with modern amenities.",
    type: "Single-family",
    yearBuilt: 2008,
    images: []
  },
  {
    id: 4,
    address: "321 Pine Road, Fairfax, VA",
    price: 850000,
    bedrooms: 6,
    bathrooms: 5,
    squareFeet: 4000,
    description: "Luxury home with a pool and large deck.",
    type: "Single-family",
    yearBuilt: 2017,
    images: []
  },
  {
    id: 5,
    address: "654 Cedar Court, Fairfax, VA",
    price: 550000,
    bedrooms: 3,
    bathrooms: 3,
    squareFeet: 2000,
    description: "Newly renovated kitchen and bathrooms.",
    type: "Townhouse",
    yearBuilt: 2012,
    images: []
  },
  {
    id: 6,
    address: "112 Birch Street, Fairfax, VA",
    price: 425000,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1500,
    description: "Perfect starter home in a great location.",
    type: "Condo",
    yearBuilt: 2006,
    images: []
  },
  {
    id: 7,
    address: "987 Willow Lane, Fairfax, VA",
    price: 680000,
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2400,
    description: "Spacious home with a finished basement.",
    type: "Single-family",
    yearBuilt: 2013,
    images: []
  },
  {
    id: 8,
    address: "444 Chestnut Avenue, Fairfax, VA",
    price: 520000,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1900,
    description: "Open floor plan with a beautiful backyard.",
    type: "Townhouse",
    yearBuilt: 2010,
    images: []
  },
  {
    id: 9,
    address: "555 Redwood Drive, Fairfax, VA",
    price: 700000,
    bedrooms: 5,
    bathrooms: 4,
    squareFeet: 3100,
    description: "Move-in ready home with updated features.",
    type: "Single-family",
    yearBuilt: 2016,
    images: []
  },
  {
    id: 10,
    address: "666 Spruce Street, Fairfax, VA",
    price: 610000,
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2300,
    description: "Great home in a desirable school district.",
    type: "Single-family",
    yearBuilt: 2009,
    images: []
  },
  {
    id: 11,
    address: "777 Fir Court, Fairfax, VA",
    price: 480000,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1700,
    description: "Charming home with modern updates.",
    type: "Single-family",
    yearBuilt: 2007,
    images: []
  },
  {
    id: 12,
    address: "888 Poplar Lane, Fairfax, VA",
    price: 725000,
    bedrooms: 5,
    bathrooms: 4,
    squareFeet: 3300,
    description: "Large home with plenty of natural light.",
    type: "Single-family",
    yearBuilt: 2018,
    images: []
  },
  {
    id: 13,
    address: "999 Cypress Road, Fairfax, VA",
    price: 780000,
    bedrooms: 6,
    bathrooms: 5,
    squareFeet: 3500,
    description: "Custom-built home with high-end finishes.",
    type: "Single-family",
    yearBuilt: 2020,
    images: []
  },
  {
    id: 14,
    address: "1011 Hawthorn Drive, Fairfax, VA",
    price: 450000,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1650,
    description: "Quiet neighborhood with excellent amenities.",
    type: "Townhouse",
    yearBuilt: 2011,
    images: []
  },
  {
    id: 15,
    address: "1022 Sycamore Lane, Fairfax, VA",
    price: 590000,
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2200,
    description: "Spacious home with updated appliances.",
    type: "Single-family",
    yearBuilt: 2014,
    images: []
  },
  {
    id: 16,
    address: "1033 Dogwood Court, Fairfax, VA",
    price: 470000,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1800,
    description: "Beautiful landscaping and curb appeal.",
    type: "Single-family",
    yearBuilt: 2008,
    images: []
  },
  {
    id: 17,
    address: "1044 Oakwood Avenue, Fairfax, VA",
    price: 825000,
    bedrooms: 5,
    bathrooms: 4,
    squareFeet: 3400,
    description: "Luxury living with a backyard patio.",
    type: "Single-family",
    yearBuilt: 2016,
    images: []
  },
  {
    id: 18,
    address: "1055 Maplewood Street, Fairfax, VA",
    price: 680000,
    bedrooms: 4,
    bathrooms: 3,
    squareFeet: 2600,
    description: "Modern home with energy-efficient features.",
    type: "Single-family",
    yearBuilt: 2015,
    images: []
  },
  {
    id: 19,
    address: "1066 Park Lane, Fairfax, VA",
    price: 530000,
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 2100,
    description: "Updated home with a spacious backyard.",
    type: "Townhouse",
    yearBuilt: 2011,
    images: []
  },
  {
    id: 20,
    address: "1077 Lincoln Street, Fairfax, VA",
    price: 750000,
    bedrooms: 5,
    bathrooms: 4,
    squareFeet: 3000,
    description: "Perfect family home in a friendly neighborhood.",
    type: "Single-family",
    yearBuilt: 2018,
    images: []
  }
];

export const singlePostData = {
  id: 1,
  title: "Luxury Home with Pool",
  price: 850000,
  images: [],
  bedrooms: 6,
  bathrooms: 5,
  squareFeet: 4000,
  latitude: 38.8462,
  longitude: -77.3064,
  city: "Fairfax",
  address: "321 Pine Road, Fairfax, VA",
  school: "1 km away",
  bus: "200 m away",
  restaurant: "500 m away",
  description: "Luxury home with pool and deck in a quiet neighborhood, built in 2017.",
};

export const userData = {
  id: 1,
  name: "Jane Smith",
  img: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
};